activation: ReLU
backcast_loss_ratio: 0.0
batch_normalization: false
categorical_groups: {}
context_length: 12
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__series_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        Avg Temperature: 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U15
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 60
          - 4
          - 8
        - false
        - !!binary |
          QQAAAHYAAABnAAAAIAAAAFQAAABlAAAAbQAAAHAAAABlAAAAcgAAAGEAAAB0AAAAdQAAAHIAAABl
          AAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - series_id
  lags: {}
  max_encoder_length: 12
  max_prediction_length: 1003
  min_encoder_length: 12
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 1003
  predict_mode: false
  randomize_length: null
  scalers: {}
  static_categoricals: null
  static_reals: null
  target: value
  target_normalizer: &id002 !!python/object:pytorch_forecasting.data.encoders.TorchNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AAAAAAAAAAA=
    method: standard
    method_kwargs: null
    scale_: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      DsAxoVED8D8=
    transformation: null
  time_idx: range_datetime
  time_varying_known_categoricals: null
  time_varying_known_reals: []
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - value
  variable_groups: null
  weight: null
downsample_frequencies:
- 1003
- 181
- 1
dropout: 0.05
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_size: 30
initialization: lecun_normal
interpolation_mode: linear
learning_rate: 0.01
log_gradient_flow: false
log_interval: -1
log_val_interval: null
monotone_constraints: {}
n_blocks:
- 1
- 1
- 1
n_layers:
- 2
- 2
- 2
naive_level: true
optimizer: adam
optimizer_params: null
output_size: 9
output_transformer: *id002
pooling_mode: max
pooling_sizes:
- 512
- 32
- 1
prediction_length: 1003
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
shared_weights: true
static_categoricals: []
static_hidden_size: 30
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- value
weight_decay: 0.001
x_categoricals: []
x_reals:
- value
